##### this code file  is to show how we build a training pipleline using a real  world dataset and using pytorch, so  dont focus on accuracy for  now

#####  everythings done manually

In [31]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [33]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [35]:
df.shape

(569, 33)

In [36]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [37]:
df.shape

(569, 31)

In [38]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

###### train test split

In [39]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [40]:
x=df.drop(columns=["diagnosis"])
y=df["diagnosis"]

In [41]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [42]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
106,11.64,18.33,75.17,412.5,0.11420,0.10170,0.07070,0.03485,0.1801,0.06520,...,13.14,29.26,85.51,521.7,0.1688,0.26600,0.28730,0.12180,0.2806,0.09097
25,17.14,16.40,116.00,912.7,0.11860,0.22760,0.22290,0.14010,0.3040,0.07413,...,22.25,21.40,152.40,1461.0,0.1545,0.39490,0.38530,0.25500,0.4066,0.10590
487,19.44,18.82,128.10,1167.0,0.10890,0.14480,0.22560,0.11940,0.1823,0.06115,...,23.96,30.39,153.90,1740.0,0.1514,0.37250,0.59360,0.20600,0.3266,0.09009
49,13.49,22.30,86.91,561.0,0.08752,0.07698,0.04751,0.03384,0.1809,0.05718,...,15.15,31.82,99.00,698.8,0.1162,0.17110,0.22820,0.12820,0.2871,0.06917
559,11.51,23.93,74.52,403.5,0.09261,0.10210,0.11120,0.04105,0.1388,0.06570,...,12.48,37.16,82.28,474.2,0.1298,0.25170,0.36300,0.09653,0.2112,0.08732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,12.31,16.52,79.19,470.9,0.09172,0.06829,0.03372,0.02272,0.1720,0.05914,...,14.11,23.21,89.71,611.1,0.1176,0.18430,0.17030,0.08660,0.2618,0.07609
69,12.78,16.49,81.37,502.5,0.09831,0.05234,0.03653,0.02864,0.1590,0.05653,...,13.46,19.76,85.67,554.9,0.1296,0.07061,0.10390,0.05882,0.2383,0.06410
458,13.00,25.13,82.61,520.2,0.08369,0.05073,0.01206,0.01762,0.1667,0.05449,...,14.34,31.88,91.06,628.5,0.1218,0.10930,0.04462,0.05921,0.2306,0.06291
27,18.61,20.25,122.10,1094.0,0.09440,0.10660,0.14900,0.07731,0.1697,0.05699,...,21.31,27.26,139.90,1403.0,0.1338,0.21170,0.34460,0.14900,0.2341,0.07421
267,13.59,21.84,87.16,561.0,0.07956,0.08259,0.04072,0.02142,0.1635,0.05859,...,14.80,30.04,97.66,661.5,0.1005,0.17300,0.14530,0.06189,0.2446,0.07024

In [43]:
y_train

106    B
25     M
487    M
49     B
559    B
      ..
74     B
69     B
458    B
27     M
267    B
Name: diagnosis, Length: 455, dtype: object

###### Scaling

In [44]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
X_train

array([[-0.72823344, -0.26759853, -0.71415116, ...,  0.08080332,
        -0.16433411,  0.34929738],
       [ 0.86313299, -0.70901345,  0.99943916, ...,  2.11796089,
         1.81708977,  1.14207981],
       [ 1.5286135 , -0.15552945,  1.50726289, ...,  1.36855608,
         0.55904287,  0.30256942],
       ...,
       [-0.33473193,  1.28764575, -0.40190252, ..., -0.87644663,
        -0.95061342, -1.14068754],
       [ 1.28846184,  0.17152927,  1.25544947, ...,  0.49679946,
        -0.89557387, -0.54065798],
       [-0.16402171,  0.53518197, -0.21094401, ..., -0.83545877,
        -0.73045521, -0.75146482]])

##### Label encoding

###### encode the target column as it aint numerical

In [46]:
from sklearn.preprocessing import LabelEncoder

In [47]:
encoder=LabelEncoder();
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

##### now,we will start working with pytorch

##### First we need to convert the numpy arrays into tensors to work with pytorch

In [48]:
X_train_tensor= torch.from_numpy(X_train)
X_test_tensor= torch.from_numpy(X_test)
y_train_tensor= torch.from_numpy(y_train)
y_test_tensor= torch.from_numpy(y_test)

In [49]:
X_train_tensor

tensor([[-0.7282, -0.2676, -0.7142,  ...,  0.0808, -0.1643,  0.3493],
        [ 0.8631, -0.7090,  0.9994,  ...,  2.1180,  1.8171,  1.1421],
        [ 1.5286, -0.1555,  1.5073,  ...,  1.3686,  0.5590,  0.3026],
        ...,
        [-0.3347,  1.2876, -0.4019,  ..., -0.8764, -0.9506, -1.1407],
        [ 1.2885,  0.1715,  1.2554,  ...,  0.4968, -0.8956, -0.5407],
        [-0.1640,  0.5352, -0.2109,  ..., -0.8355, -0.7305, -0.7515]],
       dtype=torch.float64)

##### as we can see above now our arrays are converted to tetnsors

In [50]:
X_train_tensor.shape

torch.Size([455, 30])

In [51]:
y_train_tensor.shape

torch.Size([455])

##### Define the model

In [52]:
x.shape[1] #input features

30

In [53]:
class SimpleNN():
   def __init__(self,x):
    self.weights= torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True) #for 30inputs ,initialize 30 wieghtswitht value 1
    self.bias= torch.zeros(1,dtype=torch.float64,requires_grad=True)


   def forward_pass(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred= torch.sigmoid(z)
    return y_pred

   def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #calculate loss
    loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss

#### Define NN parameters

In [54]:
learning_rate=0.1
epochs=25

##### Training pipeline

In [55]:
#create the model
model= SimpleNN(X_train_tensor)
### to train the model
# first: forward pass, calculate loss, backward pass, and parameter update
# we do these 4 things in a loop

for epoch in range(epochs):
  #forward pass
  y_pred=model.forward_pass(X_train_tensor)

  #calculate loss
  loss=model.loss_function(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #update parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'epoch:{epoch+1}, loss:{loss.item()}')

epoch:1, loss:3.334148253688536
epoch:2, loss:3.1845533904332295
epoch:3, loss:3.029864971467646
epoch:4, loss:2.870204131853103
epoch:5, loss:2.709154940553774
epoch:6, loss:2.548177751478781
epoch:7, loss:2.3873997775590077
epoch:8, loss:2.2257655006136368
epoch:9, loss:2.0659336395542716
epoch:10, loss:1.9074449257583492
epoch:11, loss:1.754432206450293
epoch:12, loss:1.6122500479799518
epoch:13, loss:1.482579060411557
epoch:14, loss:1.3669052854950046
epoch:15, loss:1.264702145084468
epoch:16, loss:1.1760593648995765
epoch:17, loss:1.1018945841023422
epoch:18, loss:1.040387237607786
epoch:19, loss:0.9917065862367067
epoch:20, loss:0.9520973909120343
epoch:21, loss:0.921369669581998
epoch:22, loss:0.897321804529506
epoch:23, loss:0.8781371637081492
epoch:24, loss:0.862411995932926
epoch:25, loss:0.8491271719473066

#####  we can see that in each epoch,loss is  reducing which is good

In [56]:
model.weights

tensor([[-0.1721],
        [-0.1955],
        [ 0.3190],
        [ 0.1647],
        [-0.1871],
        [-0.3404],
        [-0.4329],
        [ 0.0357],
        [-0.0583],
        [ 0.3484],
        [ 0.3298],
        [ 0.1893],
        [ 0.4564],
        [ 0.4992],
        [ 0.6384],
        [ 0.1315],
        [-0.4261],
        [ 0.0153],
        [-0.1544],
        [ 0.2598],
        [ 0.1696],
        [ 0.0068],
        [-0.2327],
        [-0.1951],
        [ 0.3402],
        [-0.1311],
        [ 0.3556],
        [-0.1273],
        [-0.0236],
        [-0.1810]], dtype=torch.float64, requires_grad=True)

In [57]:
model.bias

tensor([-0.0970], dtype=torch.float64, requires_grad=True)

#####  Evaluation

In [61]:
with torch.no_grad():
  y_pred=model.forward_pass(X_test_tensor)
  y_pred=(y_pred>0.9).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'accuracy:{accuracy}')
print(y_pred)

accuracy:0.6911357045173645
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])