####  Stemming->bringing  the words their root form by removing the suffixes and prefixes

##### popular stemmng alg->porter stemmer,snowball stemmer

In [1]:
import pandas as pd
import numpy as np

In [2]:
from nltk.stem.porter import PorterStemmer

In [3]:
ps=PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [4]:
txt="run runs running runned"
stem_words(txt)

'run run run run'

In [5]:
sent="The students were studying different subjects and working on their assignments."
stem_words(sent)

'the student were studi differ subject and work on their assignments.'

##### Problem with over-stemming
##### It may reduce different words to the same root, even when meanings differ.
Example:
universe → univers
university → univers

##### Problem with under-stemming
##### Sometimes it fails to reduce similar words to the same stem.
Example:
analysis → analysi
analyze → analyz

##### Problem with non-real words
##### Stems may not be valid English words.
Example:
studies → studi
relational → relat

##### Problem with ignoring context
##### It does not understand grammar or meaning.
Example:
better → better (not linked to "good")

##### Problem with English-focus
##### Mainly designed for English; less effective for other languages.
Example:
खेल्नु (Nepali "to play") → may not stem correctly

##### Lemmatization-> unlike stemming, reduces the inflected words properly ensuring that root  word belongs to the language. In lemmatization root word is called lemma. A lemma is the canonical form, dictionary form, or citation form of a set of words

In [6]:
from string import punctuation
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

nltk.download('punkt')
nltk.download('wordnet')

wordnet_lemmatizer = WordNetLemmatizer()

sentence = "Wow! The quick brown foxes were jumping over lazy dogs; they laughed, barked, and ran away."

# Tokenize
tokens = nltk.word_tokenize(sentence)
print("Tokens before removing punctuations:", tokens)

# Remove punctuations
tokens = [word for word in tokens if word not in punctuation]
print("Tokens after removing punctuations:", tokens)

# Lemmatize as VERB
for word in tokens:
    lemma = wordnet_lemmatizer.lemmatize(word, pos=wordnet.VERB)
    print("{:20}{:20}".format(word, lemma))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Tokens before removing punctuations: ['Wow', '!', 'The', 'quick', 'brown', 'foxes', 'were', 'jumping', 'over', 'lazy', 'dogs', ';', 'they', 'laughed', ',', 'barked', ',', 'and', 'ran', 'away', '.']
Tokens after removing punctuations: ['Wow', 'The', 'quick', 'brown', 'foxes', 'were', 'jumping', 'over', 'lazy', 'dogs', 'they', 'laughed', 'barked', 'and', 'ran', 'away']
Wow                 Wow
The                 The
quick               quick
brown               brown
foxes               fox
were                be
jumping             jump
over                over
lazy                lazy
dogs                dog
they                they
laughed             laugh
barked              bark
and                 and
ran                 run
away                away

#### Simple example of text-preprocessing on sample dataset

In [7]:
import requests
import pandas as pd
import numpy as np

In [8]:
url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"

In [9]:
# fetch genre details from url
movie_genre_url = "https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US"
response = requests.get(movie_genre_url)
movies_genre_details = response.json()["genres"]

In [10]:
movies_genre_details

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 80, 'name': 'Crime'},
 {'id': 99, 'name': 'Documentary'},
 {'id': 18, 'name': 'Drama'},
 {'id': 10751, 'name': 'Family'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 36, 'name': 'History'},
 {'id': 27, 'name': 'Horror'},
 {'id': 10402, 'name': 'Music'},
 {'id': 9648, 'name': 'Mystery'},
 {'id': 10749, 'name': 'Romance'},
 {'id': 878, 'name': 'Science Fiction'},
 {'id': 10770, 'name': 'TV Movie'},
 {'id': 53, 'name': 'Thriller'},
 {'id': 10752, 'name': 'War'},
 {'id': 37, 'name': 'Western'}]

In [11]:
#mapping id -> name
genre = {}
for gen in movies_genre_details:
    genre[gen["id"]] = gen["name"]

In [12]:
all_movies = []

In [13]:

# loop over pages
for page in range(1, 472):
    print(f"Fetching page {page}...")

    movies_url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={page}"
    response = requests.get(movies_url)
    data = response.json()

    # loop through each movie in this page inside the page loop
    for movie in data["results"]:
        # map genre_ids to genre names
        movies_genre_names = []
        for gen_id in movie["genre_ids"]:
            if gen_id in genre:
                movies_genre_names.append(genre[gen_id])
            else:
                movies_genre_names.append("Unknown")

        # append to all_movies
        movie_data = {
            "name": movie["title"],
            "overview": movie["overview"],
            "genre": movies_genre_names
        }
        all_movies.append(movie_data)

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Fetching page 11...
Fetching page 12...
Fetching page 13...
Fetching page 14...
Fetching page 15...
Fetching page 16...
Fetching page 17...
Fetching page 18...
Fetching page 19...
Fetching page 20...
Fetching page 21...
Fetching page 22...
Fetching page 23...
Fetching page 24...
Fetching page 25...
Fetching page 26...
Fetching page 27...
Fetching page 28...
Fetching page 29...
Fetching page 30...
Fetching page 31...
Fetching page 32...
Fetching page 33...
Fetching page 34...
Fetching page 35...
Fetching page 36...
Fetching page 37...
Fetching page 38...
Fetching page 39...
Fetching page 40...
Fetching page 41...
Fetching page 42...
Fetching page 43...
Fetching page 44...
Fetching page 45...
Fetching page 46...
Fetching page 47...
Fetching page 48...
Fetching page 49...
Fetching page 50...
Fetching page 51...
Fetching page 52...
Fetching page 53...
Fetching page 54...
Fetching page 55...
Fetching page 56...
Fetching page 57...
Fetching page 58...
Fetching page 59...
Fetching page 60...
Fetching page 61...
Fetching page 62...
Fetching page 63...
Fetching page 64...
Fetching page 65...
Fetching page 66...
Fetching page 67...
Fetching page 68...
Fetching page 69...
Fetching page 70...
Fetching page 71...
Fetching page 72...
Fetching page 73...
Fetching page 74...
Fetching page 75...
Fetching page 76...
Fetching page 77...
Fetching page 78...
Fetching page 79...
Fetching page 80...
Fetching page 81...
Fetching page 82...
Fetching page 83...
Fetching page 84...
Fetching page 85...
Fetching page 86...
Fetching page 87...
Fetching page 88...
Fetching page 89...
Fetching page 90...
Fetching page 91...
Fetching page 92...
Fetching page 93...
Fetching page 94...
Fetching page 95...
Fetching page 96...
Fetching page 97...
Fetching page 98...
Fetching page 99...
Fetching page 100...
Fetching page 101...
Fetching page 102...
Fetching page 103...
Fetching page 104...
Fetching page 105...
Fetching page 106...
Fetching page 107...
Fetching page 108...
Fetching page 109...
Fetching page 110...
Fetching page 111...
Fetching page 112...
Fetching page 113...
Fetching page 114...
Fetching page 115...
Fetching page 116...
Fetching page 117...
Fetching page 118...
Fetching page 119...
Fetching page 120...
Fetching page 121...
Fetching page 122...
Fetching page 123...
Fetching page 124...
Fetching page 125...
Fetching page 126...
Fetching page 127...
Fetching page 128...
Fetching page 129...
Fetching page 130...
Fetching page 131...
Fetching page 132...
Fetching page 133...
Fetching page 134...
Fetching page 135...
Fetching page 136...
Fetching page 137...
Fetching page 138...
Fetching page 139...
Fetching page 140...
Fetching page 141...
Fetching page 142...
Fetching page 143...
Fetching page 144...
Fetching page 145...
Fetching page 146...
Fetching page 147...
Fetching page 148...
Fetching page 149...
Fetching page 150...
Fetching page 151...
Fetching page 152...
Fetching page 153...
Fetching page 154...
Fetching page 155...
Fetching page 156...
Fetching page 157...
Fetching page 158...
Fetching page 159...
Fetching page 160...
Fetching page 161...
Fetching page 162...
Fetching page 163...
Fetching page 164...
Fetching page 165...
Fetching page 166...
Fetching page 167...
Fetching page 168...
Fetching page 169...
Fetching page 170...
Fetching page 171...
Fetching page 172...
Fetching page 173...
Fetching page 174...
Fetching page 175...
Fetching page 176...
Fetching page 177...
Fetching page 178...
Fetching page 179...
Fetching page 180...
Fetching page 181...
Fetching page 182...
Fetching page 183...
Fetching page 184...
Fetching page 185...
Fetching page 186...
Fetching page 187...
Fetching page 188...
Fetching page 189...
Fetching page 190...
Fetching page 191...
Fetching page 192...
Fetching page 193...
Fetching page 194...
Fetching page 195...
Fetching page 196...
Fetching page 197...
Fetching page 198...
Fetching page 199...
Fetching page 200...
Fetching page 201...
Fetching page 202...
Fetching page 203...
Fetching page 204...
Fetching page 205...
Fetching page 206...
Fetching page 207...
Fetching page 208...
Fetching page 209...
Fetching page 210...
Fetching page 211...
Fetching page 212...
Fetching page 213...
Fetching page 214...
Fetching page 215...
Fetching page 216...
Fetching page 217...
Fetching page 218...
Fetching page 219...
Fetching page 220...
Fetching page 221...
Fetching page 222...
Fetching page 223...
Fetching page 224...
Fetching page 225...
Fetching page 226...
Fetching page 227...
Fetching page 228...
Fetching page 229...
Fetching page 230...
Fetching page 231...
Fetching page 232...
Fetching page 233...
Fetching page 234...
Fetching page 235...
Fetching page 236...
Fetching page 237...
Fetching page 238...
Fetching page 239...
Fetching page 240...
Fetching page 241...
Fetching page 242...
Fetching page 243...
Fetching page 244...
Fetching page 245...
Fetching page 246...
Fetching page 247...
Fetching page 248...
Fetching page 249...
Fetching page 250...
Fetching page 251...
Fetching page 252...
Fetching page 253...
Fetching page 254...
Fetching page 255...
Fetching page 256...
Fetching page 257...
Fetching page 258...
Fetching page 259...
Fetching page 260...
Fetching page 261...
Fetching page 262...
Fetching page 263...
Fetching page 264...
Fetching page 265...
Fetching page 266...
Fetching page 267...
Fetching page 268...
Fetching page 269...
Fetching page 270...
Fetching page 271...
Fetching page 272...
Fetching page 273...
Fetching page 274...
Fetching page 275...
Fetching page 276...
Fetching page 277...
Fetching page 278...
Fetching page 279...
Fetching page 280...
Fetching page 281...
Fetching page 282...
Fetching page 283...
Fetching page 284...
Fetching page 285...
Fetching page 286...
Fetching page 287...
Fetching page 288...
Fetching page 289...
Fetching page 290...
Fetching page 291...
Fetching page 292...
Fetching page 293...
Fetching page 294...
Fetching page 295...
Fetching page 296...
Fetching page 297...
Fetching page 298...
Fetching page 299...
Fetching page 300...
Fetching page 301...
Fetching page 302...
Fetching page 303...
Fetching page 304...
Fetching page 305...
Fetching page 306...
Fetching page 307...
Fetching page 308...
Fetching page 309...
Fetching page 310...
Fetching page 311...
Fetching page 312...
Fetching page 313...
Fetching page 314...
Fetching page 315...
Fetching page 316...
Fetching page 317...
Fetching page 318...
Fetching page 319...
Fetching page 320...
Fetching page 321...
Fetching page 322...
Fetching page 323...
Fetching page 324...
Fetching page 325...
Fetching page 326...
Fetching page 327...
Fetching page 328...
Fetching page 329...
Fetching page 330...
Fetching page 331...
Fetching page 332...
Fetching page 333...
Fetching page 334...
Fetching page 335...
Fetching page 336...
Fetching page 337...
Fetching page 338...
Fetching page 339...
Fetching page 340...
Fetching page 341...
Fetching page 342...
Fetching page 343...
Fetching page 344...
Fetching page 345...
Fetching page 346...
Fetching page 347...
Fetching page 348...
Fetching page 349...
Fetching page 350...
Fetching page 351...
Fetching page 352...
Fetching page 353...
Fetching page 354...
Fetching page 355...
Fetching page 356...
Fetching page 357...
Fetching page 358...
Fetching page 359...
Fetching page 360...
Fetching page 361...
Fetching page 362...
Fetching page 363...
Fetching page 364...
Fetching page 365...
Fetching page 366...
Fetching page 367...
Fetching page 368...
Fetching page 369...
Fetching page 370...
Fetching page 371...
Fetching page 372...
Fetching page 373...
Fetching page 374...
Fetching page 375...
Fetching page 376...
Fetching page 377...
Fetching page 378...
Fetching page 379...
Fetching page 380...
Fetching page 381...
Fetching page 382...
Fetching page 383...
Fetching page 384...
Fetching page 385...
Fetching page 386...
Fetching page 387...
Fetching page 388...
Fetching page 389...
Fetching page 390...
Fetching page 391...
Fetching page 392...
Fetching page 393...
Fetching page 394...
Fetching page 395...
Fetching page 396...
Fetching page 397...
Fetching page 398...
Fetching page 399...
Fetching page 400...
Fetching page 401...
Fetching page 402...
Fetching page 403...
Fetching page 404...
Fetching page 405...
Fetching page 406...
Fetching page 407...
Fetching page 408...
Fetching page 409...
Fetching page 410...
Fetching page 411...
Fetching page 412...
Fetching page 413...
Fetching page 414...
Fetching page 415...
Fetching page 416...
Fetching page 417...
Fetching page 418...
Fetching page 419...
Fetching page 420...
Fetching page 421...
Fetching page 422...
Fetching page 423...
Fetching page 424...
Fetching page 425...
Fetching page 426...
Fetching page 427...
Fetching page 428...
Fetching page 429...
Fetching page 430...
Fetching page 431...
Fetching page 432...
Fetching page 433...
Fetching page 434...
Fetching page 435...
Fetching page 436...
Fetching page 437...
Fetching page 438...
Fetching page 439...
Fetching page 440...
Fetching page 441...
Fetching page 442...
Fetching page 443...
Fetching page 444...
Fetching page 445...
Fetching page 446...
Fetching page 447...
Fetching page 448...
Fetching page 449...
Fetching page 450...
Fetching page 451...
Fetching page 452...
Fetching page 453...
Fetching page 454...
Fetching page 455...
Fetching page 456...
Fetching page 457...
Fetching page 458...
Fetching page 459...
Fetching page 460...
Fetching page 461...
Fetching page 462...
Fetching page 463...
Fetching page 464...
Fetching page 465...
Fetching page 466...
Fetching page 467...
Fetching page 468...
Fetching page 469...
Fetching page 470...
Fetching page 471...

In [14]:
print(all_movies[:5])

[{'name': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'genre': ['Drama', 'Crime']}, {'name': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'genre': ['Drama', 'Crime']}, {'name': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'genre': ['Drama', 'Crime']}, {'name': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'genre': ['Drama', 'History', 'War']}, {'name': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'genre': ['Drama']}]

In [15]:
df=pd.DataFrame(all_movies)

In [16]:
df.head()

,name,overview,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[Drama, Crime]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Drama, Crime]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Drama, Crime]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[Drama, History, War]"
4,12 Angry Men,The defense and the prosecution have rested an...,[Drama]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9420 entries, 0 to 9419
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      9420 non-null   object
 1   overview  9420 non-null   object
 2   genre     9420 non-null   object
dtypes: object(3)
memory usage: 220.9+ KB

In [18]:
df.isnull().sum()

name        0
overview    0
genre       0
dtype: int64